# Generated by Django 4.2.4 on 2023-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupapi', '0002_bloodgroup_community_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
