# Generated by Django 4.2.4 on 2023-10-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupapi', '0003_alter_religion_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
