# Generated by Django 4.2.4 on 2023-10-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupapi', '0008_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('districtId', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
