# Generated by Django 4.2.4 on 2023-11-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupapi', '0009_taluk'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
