# Generated by Django 4.2.4 on 2023-10-08 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='frontend/src/assets/preview-profile.png', upload_to='students')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('nationality', models.CharField(max_length=10, null=True)),
                ('religion', models.CharField(max_length=30)),
                ('community', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=70)),
                ('aadhar', models.CharField(max_length=12, unique=True)),
                ('firstgraduate', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('emailid', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('location_type', models.CharField(max_length=5)),
                ('taluk', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('fathersname', models.CharField(max_length=100)),
                ('fathersoccupation', models.CharField(max_length=100)),
                ('mothersname', models.CharField(max_length=100)),
                ('mothersoccupation', models.CharField(max_length=100)),
                ('annual_income', models.CharField(max_length=50)),
                ('parents_mobile_number', models.CharField(max_length=15)),
                ('account_number', models.CharField(max_length=50, null=True)),
                ('ifsc', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLoginModel',
            fields=[
                ('studentsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentApi.studentsmodel')),
                ('userid', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            bases=('StudentApi.studentsmodel',),
        ),
    ]
