# Generated by Django 4.2.4 on 2023-10-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='profile',
            field=models.ImageField(null=True, upload_to='students'),
        ),
    ]
