# Generated by Django 4.2.4 on 2023-10-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApi', '0002_alter_studentsmodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='bloodgroup',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='caste',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='community',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='country',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='district',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='emailid',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='gender',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='religion',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='state',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='taluk',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
