# Generated by Django 4.2.4 on 2023-11-01 14:15

import StudentApi.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApi', '0003_alter_studentsmodel_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='dob',
            field=StudentApi.models.DateMonthYearField(),
        ),
    ]
