# Generated by Django 4.2.4 on 2023-11-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApi', '0004_alter_studentsmodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='pincode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
