# Generated by Django 4.2.7 on 2023-12-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApi', '0004_studentsmodel_academic_year_studentsmodel_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='rollno',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
