# Generated by Django 4.2.7 on 2023-12-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApi', '0005_studentsmodel_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='joined',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
