# Generated by Django 4.2.4 on 2023-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApi', '0005_studentsmodel_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
