# Generated by Django 4.2.7 on 2023-12-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApi', '0006_studentsmodel_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='academic_year',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
